// Intent Registry
// All intent definitions for GPT-based classification

import type { IntentDefinition } from '../types';

export const intentRegistry: IntentDefinition[] = [
  // === TRADES DOMAIN ===
  {
    id: 'trades.profitable',
    domain: 'trades',
    cardType: 'profitable',
    description: 'User asks about profitable trades, gains, winners, or profit/loss for a symbol',
    examples: [
      'Show my profitable trades for Apple',
      'What were my gains on TSLA?',
      'Did I make money on Google?',
      'Most profitable trade on SPY',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: ['timePeriod'],
  },
  {
    id: 'trades.detailed',
    domain: 'trades',
    cardType: 'detailed',
    description: 'User wants to see all trades or trade history for a symbol',
    examples: [
      'Show my Apple trades',
      'List all TSLA trades',
      'What did I trade for Google?',
      'My Tesla trade history',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: ['timePeriod', 'tradeType'],
  },
  {
    id: 'trades.time_based',
    domain: 'trades',
    cardType: 'time-based',
    description: 'User asks about GENERAL trades during a time period. DO NOT use this if query mentions calls, puts, options, premium, strike, short, or long - those are OPTIONS intents.',
    examples: [
      'What did I trade yesterday?',
      'Show trades from last week',
      'My trades this month',
      'What did I trade on Monday?',
      'AAPL trades last month',
      'Show my trades for the past four days',
      'What did I trade in the last 5 days?',
      'Trades from the past ten days',
      // Date range examples
      'Show my trades from June 1st to the 7th',
      'Trades in August and September',
      'What did I trade from November 15 to December 5?',
      // Discrete date examples
      'Show my trades for July 1st and August 1st',
      'Trades on January 5th, March 10th and June 20th',
      // Quarter-based examples
      'What did I trade last quarter?',
      'Show my trades for Q3',
      'Trades in the first quarter',
      'What did I trade in Q2 2025?',
      // Single month examples
      'What did I trade in January?',
      'Show my February trades',
      // Half-year examples
      'Trades in the first half of the year',
      'What did I trade in H2?',
    ],
    requiredEntities: ['timePeriod'],
    optionalEntities: ['symbol'],
  },
  {
    id: 'trades.stats',
    domain: 'trades',
    cardType: 'stats',
    description: 'User asks about price statistics: highest, lowest, average price paid or sold',
    examples: [
      'What was the highest price I sold Apple for?',
      'Lowest price I bought Tesla?',
      'Average buy price for NVDA this year',
      'What was my best sale price for SPY?',
      // Quarter-based examples
      'Highest price I sold Apple last quarter',
      'What was the lowest price I bought Tesla in Q3?',
      'Average price for AAPL in the first quarter',
      // Single month examples
      'Highest price sold in January',
      'What did I buy GOOGL for in March?',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: ['tradeType', 'timePeriod'],
  },
  {
    id: 'trades.summary',
    domain: 'trades',
    cardType: 'summary',
    description: 'User asks how many trades they have for a symbol',
    examples: [
      'How many Apple trades do I have?',
      'Count my TSLA trades',
      'Number of Google trades',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: [],
  },
  {
    id: 'trades.average_price',
    domain: 'trades',
    cardType: 'average-price',
    description: 'User specifically asks for average price only (not full stats)',
    examples: [
      'What was the average price I paid for Apple?',
      'Average cost basis for TSLA',
      'What did I average into Google at?',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: ['tradeType', 'timePeriod'],
  },

  // === OPTIONS DOMAIN ===
  {
    id: 'options.bulk',
    domain: 'options',
    cardType: 'advanced-options',
    description: 'User asks about multiple option trades: all calls, all puts, short options, long options. IMPORTANT: Use this intent whenever calls/puts/options are mentioned with a time period.',
    examples: [
      'Show all my short calls on Tesla',
      'My put options on Apple',
      'All the calls I sold last month',
      'Long puts on SPY',
      'Option trades on NVDA',
      'Show all Short call options on TSLA last month',
      'Short puts I sold this year',
      'All my call options from last week',
      // Date range examples
      'Options I sold from June 1st to the 7th',
      'Call options in August and September',
      'Puts I bought from November 15 to December 5',
    ],
    requiredEntities: [],
    optionalEntities: ['symbol', 'callPut', 'tradeType', 'timePeriod'],
  },
  {
    id: 'options.last_trade',
    domain: 'options',
    cardType: 'last-option',
    description: 'User asks about their SINGLE last, most recent, or latest option trade. Keywords: "last", "most recent", "latest" before option/call/put. Note: "options" plural still means single most recent!',
    examples: [
      'Show my last call option on Apple',
      'Most recent put I bought',
      'Latest option trade on TSLA',
      'Show last call options I bought on AAPL',
      'Show the last call options I bought in Apple',
      'What was my last put option?',
      'Show me the most recent call I sold',
      'Last put options I sold',
    ],
    requiredEntities: [],
    optionalEntities: ['symbol', 'callPut', 'tradeType'],
  },
  {
    id: 'options.expiring',
    domain: 'options',
    cardType: 'expiring-options',
    description: 'User asks about options EXPIRING soon (tomorrow, this week, this month). Keywords: "expiring", "expire", "expiration".',
    examples: [
      'What options expire tomorrow?',
      'Options expiring this week',
      'Do I have anything expiring this month?',
      'Show me all options expiring tomorrow',
      'Which options are expiring this week?',
      'Any positions expiring soon?',
    ],
    requiredEntities: ['expiration'],
    optionalEntities: ['symbol'],
  },
  {
    id: 'options.highest_strike',
    domain: 'options',
    cardType: 'highest-strike',
    description: 'User asks about HIGHEST or LOWEST strike price option. Keywords: "highest strike", "lowest strike".',
    examples: [
      'What was my highest strike call on Apple?',
      'Lowest strike put I sold',
      'Highest strike call option I sold on AAPL this year',
      'What is the highest strike put I bought?',
      'Show my lowest strike call',
    ],
    requiredEntities: ['callPut'],
    optionalEntities: ['symbol', 'tradeType', 'timePeriod'],
  },
  {
    id: 'options.total_premium',
    domain: 'options',
    cardType: 'total-premium',
    description: 'User asks about TOTAL premium collected or paid for options. Keywords: "total premium", "premium collected", "premium paid".',
    examples: [
      'How much premium did I collect on SPY?',
      'Total premium paid for AAPL calls',
      'Premium collected last month',
      'Total premium I paid for buying SPY options last 12 months',
      'How much premium have I collected this year?',
      'What is my total premium from selling puts?',
      // Date range examples
      'Premium collected from June 1st to the 7th',
      'Total premium in August and September',
    ],
    requiredEntities: [],
    optionalEntities: ['symbol', 'tradeType', 'timePeriod'],
  },

  // === ACCOUNT DOMAIN ===
  {
    id: 'account.summary',
    domain: 'account',
    cardType: 'account-balance',
    description: 'User asks about account balance, equity, buying power, margin, or general account info',
    examples: [
      'What is my account balance?',
      'How much money can I withdraw?',
      'How much money do I have?',
      'How much buying power do I have?',
      'Show my account equity',
      'Show my account summary',
      'What is my margin requirement?',
      'Cash balance in my account',
      'Net liquidation value',
      'Debit balances for the month',
      'Credit balances for the month',
    ],
    requiredEntities: ['accountQueryType'],
    optionalEntities: ['timePeriod'],
  },

  // === FEES DOMAIN ===
  {
    id: 'fees.query',
    domain: 'fees',
    cardType: 'fees',
    description: 'User asks about fees, commissions, interest charges, locate fees, or short interest (borrow fees for shorting stocks)',
    examples: [
      'How much did I pay in commissions?',
      'Interest charges this month',
      'Locate fees for GME',
      'Total fees last year',
      // Date range examples
      'Commissions from June 1st to the 7th',
      'What were my commissions in August and September?',
      'Interest charges from November 15 to December 5',
      // Discrete date examples
      'Commissions on July 1st and August 1st',
      // Short interest examples
      'Short interest from last month',
      'What is my short interest for this year?',
      'Show my short interest',
      'How much short interest did I pay?',
      'Short interest for MTEN',
    ],
    requiredEntities: ['feeType'],
    optionalEntities: ['symbol', 'timePeriod'],
  },

  // === MARKET DATA DOMAIN ===
  {
    id: 'market.stock_quote',
    domain: 'market',
    cardType: 'stock-quote',
    description: 'User asks for current stock price, quote, last trade, or NBBO. This is for REAL-TIME market prices, not historical trade data from their portfolio.',
    examples: [
      'What is AAPL trading at?',
      'Quote MSFT',
      'Last price for Tesla',
      'How much is SPY right now?',
      'Current price of Google',
      'What is the last for AAPL?',
      'Price of IBKR',
      'Inside market AAPL',
      'NBBO for Apple',
      'Bid and ask for TSLA',
      'What is mid of IBKR?',
      'Show me the bid of NVDA',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: [],
  },
  {
    id: 'market.option_quote',
    domain: 'market',
    cardType: 'option-quote',
    description: 'User asks for current option quote, NBBO, bid, ask, or mid price for an option contract. Requires underlying symbol, strike, and call/put type.',
    examples: [
      'Quote SPY Dec 16 strike 200 call',
      'What is NBBO of SPY 105 call Dec 16',
      'Show me bid of SPY Dec16 105 CALL',
      'What is last for SPY Dec16 105 call',
      'NBBO for SPY expiring on December 16 105 call',
      'Bid ask and last for AAPL Jan 200 call',
      'Mid price for TSLA Feb 250 put',
      'Inside market on Tesla 300 call',
    ],
    requiredEntities: ['symbol', 'strike', 'callPut'],
    optionalEntities: ['expiration'],
  },
  {
    id: 'market.historical_chart',
    domain: 'market',
    cardType: 'price-chart',
    description: 'User asks for price chart, historical price data, or price history for a stock',
    examples: [
      'Show 3 week chart for AAPL',
      '1 month chart TSLA',
      'Price history for SPY last week',
      'Show me NVDA chart',
      'Chart for Apple',
      'Historical prices for Google',
      'Show price chart for Meta',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: ['chartPeriod'],
  },
  {
    id: 'market.news',
    domain: 'market',
    cardType: 'news',
    description: 'User asks for news about a stock or the market in general',
    examples: [
      'News for MSFT',
      'What is the latest news on Tesla?',
      'Any news about Apple?',
      'Show me market news',
      'AAPL news',
      'What is happening with Google?',
    ],
    requiredEntities: [],
    optionalEntities: ['symbol'],
  },
  {
    id: 'market.halt_status',
    domain: 'market',
    cardType: 'halt-status',
    description: 'User asks about trading halts, whether a stock is halted, or market status',
    examples: [
      'Is there a halt on GME?',
      'Trading halts',
      'Is AAPL halted?',
      'Check halt status',
      'Is the market open?',
      'What is the market status?',
    ],
    requiredEntities: [],
    optionalEntities: ['symbol'],
  },

  // === FUNDAMENTALS DOMAIN ===
  {
    id: 'fundamentals.overview',
    domain: 'fundamentals',
    cardType: 'company-overview',
    description: 'User asks about company info, business summary, what a company does, or general fundamentals overview',
    examples: [
      'Tell me about AAPL',
      'Business summary for Apple',
      'What does Tesla do?',
      'Company overview for MSFT',
      'Show me fundamentals for Google',
      'What is Amazon?',
      'Describe Nvidia',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: [],
  },
  {
    id: 'fundamentals.metric',
    domain: 'fundamentals',
    cardType: 'fundamental-metric',
    description: 'User asks for a specific financial metric like PE ratio, market cap, beta, margins, ratios, or 52-week high/low',
    examples: [
      'PE ratio for MSFT',
      'Market cap of Apple',
      '52 week high for BAC',
      '52 week low for Tesla',
      'Beta for NVDA',
      'Gross margin for Google',
      'Operating margin for Amazon',
      'Quick ratio for JPM',
      'Current ratio for MSFT',
      'Debt to equity for Apple',
      'Return on equity for Tesla',
      'Dividend yield for KO',
      'EPS for Amazon',
      'Book value per share for BAC',
      'Free cash flow for Microsoft',
      'Price to revenue for AAPL',
      'Payout ratio for JNJ',
    ],
    requiredEntities: ['symbol', 'metricType'],
    optionalEntities: [],
  },
  {
    id: 'fundamentals.financials',
    domain: 'fundamentals',
    cardType: 'financials',
    description: 'User asks about financial statements, revenue, income, balance sheet, or cash flow items',
    examples: [
      'Revenue for Apple',
      'Show income statement for MSFT',
      'Balance sheet for Tesla',
      'Cash flow for Amazon',
      'Net income for Google',
      'Total assets for JPM',
      'Total liabilities for BAC',
      'Operating income for NVDA',
      'Cost of revenue for AAPL',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: ['statementType'],
  },
  {
    id: 'fundamentals.earnings',
    domain: 'fundamentals',
    cardType: 'earnings',
    description: 'User asks about earnings date, earnings calendar, or when a company reports',
    examples: [
      'When is Apple earnings?',
      'Earnings date for MSFT',
      'When does Tesla report?',
      'Upcoming earnings',
      'Next earnings for Amazon',
      'Earnings calendar',
      'Show upcoming earnings',
    ],
    requiredEntities: [],
    optionalEntities: ['symbol'],
  },
  {
    id: 'fundamentals.dividend',
    domain: 'fundamentals',
    cardType: 'dividend',
    description: 'User asks about dividends, dividend history, dividend dates, or dividend yield',
    examples: [
      'Dividends for Apple',
      'What is the dividend for MSFT?',
      'Ex-dividend date for JPM',
      'Dividend history for KO',
      'When is the next dividend for JNJ?',
      'Show me upcoming dividends',
      'Dividend date for Apple',
    ],
    requiredEntities: ['symbol'],
    optionalEntities: [],
  },

  // === CONTEXTUAL DOMAIN ===
  {
    id: 'contextual.time_period_followup',
    domain: 'contextual',
    cardType: 'contextual-followup',
    description: 'User is asking a FOLLOW-UP question to change the time period of a previous query. These are SHORT queries that reference a new time period WITHOUT repeating the original subject (fees, trades, account, etc.). The new time period will be applied to whatever was previously discussed.',
    examples: [
      'And what about last month?',
      'How about this year?',
      'What about last three months?',
      'And for October?',
      'Same for last week',
      'What was it for last quarter?',
      'And yesterday?',
      'How much in Q3?',
      'What about the first half of the year?',
      'And what is this year?',
      'So how much for the last six months?',
    ],
    requiredEntities: ['timePeriod'],
    optionalEntities: [],
  },
];
